version: '3.8'

services:
  flask-app-1:
    build:
      context: .
      dockerfile: postgres.Dockerfile
    container_name: flask-app-1
    environment:
      - DATABASE_URL=postgresql://flaskuser:flaskpass@postgres-db:5432/flaskdb
    depends_on:
      - postgres-db

  flask-app-2:
    build:
      context: .
      dockerfile:  python.Dockerfile
    container_name: flask-app-2
    environment:
      - DATABASE_URL=postgresql://flaskuser:flaskpass@postgres-db:5432/flaskdb
    depends_on:
      - postgres-db
    ports:
    - "5000:5000"  # <-- adiciona essa linha para expor porta


  postgres-db:
    image: postgres:13-alpine
    container_name: postgres-db
    environment:
      - POSTGRES_DB=flaskdb
      - POSTGRES_USER=flaskuser
      - POSTGRES_PASSWORD=flaskpass
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  nginx:
    image: nginx:alpine
    container_name: nginx-balancer
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - flask-app-1
      - flask-app-2

volumes:
  postgres-data:
